### ISSUE TITLE
Battery border doesn’t update outside control center

### ISSUE THREAD

**Issue by machineonamission** [ExeRhythm/batterain#1]
Title
In app/Home Screen, installed tweak at 19% and charged to this
![6653F9BA-2F9E-469E-8BC6-A692AF61A0D6](https://user-images.githubusercontent.com/35177464/143186642-8107725d-802a-44ca-8684-fb6faf31a5e9.jpeg)
In control center
![8B43E01C-4D46-488A-9E97-66BDC11488CF](https://user-images.githubusercontent.com/35177464/143186650-466deca9-5d8b-48e6-8b96-bdcb26fe2a10.jpeg)

**Comment by sourcelocation** [comment]
Thanks for creating an issue! I'll look into that right now

**Comment by machineonamission** [comment]
Seems to also fix itself when locking and unlocking, might only be an issue if the device is left open and unlocked?

**Comment by sourcelocation** [comment]
Fixed in 1.1
